#include "../include/Map.hpp"

Map::Map() {
    map = {
        {Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall,
         Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall},
        {Tile::Wall, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Wall,
         Tile::Dot,  Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Wall},
        {Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot, Tile::Wall,
         Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall},
        {Tile::Wall, Tile::PowerPellet, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,         Tile::Wall,
         Tile::Wall, Tile::Wall,        Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall,        Tile::Wall,
         Tile::Wall, Tile::Dot,         Tile::Wall, Tile::Wall, Tile::Wall, Tile::PowerPellet, Tile::Wall},
        {Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot, Tile::Wall,
         Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall},
        {Tile::Wall, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot,
         Tile::Dot,  Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Wall},
        {Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall,
         Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall},
        {Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall,
         Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall},
        {Tile::Wall, Tile::Dot, Tile::Dot, Tile::Dot,  Tile::Dot, Tile::Dot, Tile::Wall, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Wall,
         Tile::Dot,  Tile::Dot, Tile::Dot, Tile::Wall, Tile::Dot, Tile::Dot, Tile::Dot,  Tile::Dot, Tile::Dot, Tile::Wall},
        {Tile::Wall,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Empty, Tile::Wall,
         Tile::Empty, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall},
        {Tile::Wall,  Tile::Wall,  Tile::Wall,  Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Empty, Tile::Empty, Tile::Empty, Tile::Empty,
         Tile::Empty, Tile::Empty, Tile::Empty, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall,  Tile::Wall,  Tile::Wall},
        {Tile::Wall,  Tile::Wall, Tile::Wall, Tile::Wall,           Tile::Wall, Tile::Dot,  Tile::Wall,
         Tile::Empty, Tile::Wall, Tile::Wall, Tile::GhostHouseDoor, Tile::Wall, Tile::Wall, Tile::Empty,
         Tile::Wall,  Tile::Dot,  Tile::Wall, Tile::Wall,           Tile::Wall, Tile::Wall, Tile::Wall},
        {Tile::Wall,  Tile::Wall, Tile::Wall,       Tile::Wall,       Tile::Wall,       Tile::Dot,  Tile::Wall,
         Tile::Empty, Tile::Wall, Tile::GhostHouse, Tile::GhostHouse, Tile::GhostHouse, Tile::Wall, Tile::Empty,
         Tile::Wall,  Tile::Dot,  Tile::Wall,       Tile::Wall,       Tile::Wall,       Tile::Wall, Tile::Wall},
        {Tile::EscapeTunnel, Tile::Empty, Tile::Empty,      Tile::Empty,      Tile::Empty,      Tile::Dot,   Tile::Empty,
         Tile::Empty,        Tile::Wall,  Tile::GhostHouse, Tile::GhostHouse, Tile::GhostHouse, Tile::Wall,  Tile::Empty,
         Tile::Empty,        Tile::Dot,   Tile::Empty,      Tile::Empty,      Tile::Empty,      Tile::Empty, Tile::EscapeTunnel},
        {Tile::Wall, Tile::Wall, Tile::Wall,  Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Empty, Tile::Wall, Tile::Wall, Tile::Wall,
         Tile::Wall, Tile::Wall, Tile::Empty, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall,  Tile::Wall, Tile::Wall},
        {Tile::Wall,  Tile::Wall,  Tile::Wall,  Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Empty, Tile::Empty, Tile::Empty, Tile::Empty,
         Tile::Empty, Tile::Empty, Tile::Empty, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall,  Tile::Wall,  Tile::Wall},
        {Tile::Wall, Tile::Wall, Tile::Wall,  Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Empty, Tile::Wall, Tile::Wall, Tile::Wall,
         Tile::Wall, Tile::Wall, Tile::Empty, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall,  Tile::Wall, Tile::Wall},
        {Tile::Wall, Tile::Wall, Tile::Wall,  Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Empty, Tile::Wall, Tile::Wall, Tile::Wall,
         Tile::Wall, Tile::Wall, Tile::Empty, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall,  Tile::Wall, Tile::Wall},
        {Tile::Wall, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Wall,
         Tile::Dot,  Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Wall},
        {Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot, Tile::Wall,
         Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall},
        {Tile::Wall, Tile::PowerPellet, Tile::Dot, Tile::Dot, Tile::Wall, Tile::Dot,  Tile::Dot, Tile::Dot, Tile::Dot,         Tile::Dot, Tile::Empty,
         Tile::Dot,  Tile::Dot,         Tile::Dot, Tile::Dot, Tile::Dot,  Tile::Wall, Tile::Dot, Tile::Dot, Tile::PowerPellet, Tile::Wall},
        {Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall,
         Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall},
        {Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall,
         Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall},
        {Tile::Wall, Tile::Dot, Tile::Dot, Tile::Dot,  Tile::Dot, Tile::Dot, Tile::Wall, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Wall,
         Tile::Dot,  Tile::Dot, Tile::Dot, Tile::Wall, Tile::Dot, Tile::Dot, Tile::Dot,  Tile::Dot, Tile::Dot, Tile::Wall},
        {Tile::Wall, Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot, Tile::Wall,
         Tile::Dot,  Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Dot,  Tile::Wall},
        {Tile::Wall, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Wall,
         Tile::Dot,  Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Dot, Tile::Wall},
        {Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall,
         Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall, Tile::Wall}
    };
};